- cluster/apps/database/stackgres/helm-release.yaml
- cluster/crds/stackgres/crds.yaml
Reverts tyriis/flux.k3s.cluster#392
> Revert "chore(deps): update helm release stackgres-operator to v1.2.1"

- cluster/crds/cert-manager/kustomization.yaml
Reverts tyriis/flux.k3s.cluster#800
> Revert "chore(deps): update dependency cert-manager/cert-manager to v1.10.1"

- cluster/apps/home/emqx/helm-release.yaml
Reverts tyriis/flux.k3s.cluster#1001
> Revert "chore(deps): update helm release emqx to v5.0.16"

- kubernetes/apps/observability/loki/app/helm-release.yaml
> Revert "chore(deps): update helm release loki to v5.5.3"

- kubernetes/apps/observability/loki/app/helm-release.yaml
> Revert "chore(deps): update helm release loki to v5.5.4"

- kubernetes/talos-flux/apps/observability/loki/app/helm-release.yaml
> Revert "fix(loki): refinement"

- kubernetes/talos-flux/apps/traefik-ingress/traefik/app/helm-release.yaml
> Revert "Revert "feat(traefik)!: Update helm-release ( 27.0.2 → 28.0.0 )""

- kubernetes/talos-flux/apps/database/cloudnative-pg/cluster/cluster.yaml
> Revert "feat(container)!: Update image ghcr.io/cloudnative-pg/postgresql ( 15.7-1 → 16.3-1 )"

- kubernetes/talos-flux/apps/database/cloudnative-pg/cluster/database-server.yaml
- kubernetes/talos-flux/apps/database/cloudnative-pg/cluster/kustomization.yaml
- kubernetes/talos-flux/apps/database/cloudnative-pg/flux-sync.yaml
- kubernetes/talos-flux/apps/database/dbman/flux-sync.yaml
- kubernetes/talos-flux/apps/database/dbman/operator/helm-release.yaml
- kubernetes/talos-flux/apps/database/dbman/operator/kustomization.yaml
- kubernetes/talos-flux/apps/home-automation/home-assistant/app/database.yaml
- kubernetes/talos-flux/apps/home-automation/home-assistant/app/helm-release.yaml
- kubernetes/talos-flux/apps/home-automation/home-assistant/app/kustomization.yaml
- kubernetes/talos-flux/flux/repositories/helm/dbman-charts.yaml
> feat(dbman): setup #3045

- kubernetes/talos-flux/flux/flux-manifests/kustomization.yaml
values are related to current usage (spikes in CPU not considered)
limits left unset will fallback to default values, possible to set them accordingly.
> fix(flux): adapt resource requests and limits

- kubernetes/talos-flux/apps/database/cloudnative-pg/cluster/cluster16.yaml
- kubernetes/talos-flux/apps/database/cloudnative-pg/cluster/database-server.yaml
- kubernetes/talos-flux/apps/database/cloudnative-pg/cluster/kustomization.yaml
- kubernetes/talos-flux/apps/database/cloudnative-pg/cluster/scheduled-backup.yaml
- kubernetes/talos-flux/apps/home-automation/home-assistant/app/database.yaml
- kubernetes/talos-flux/apps/home-automation/home-assistant/app/home-assistant-secrets.sops.yaml
resolves https://github.com/tyriis/home-ops/issues/2965 and https://github.com/tyriis/home-ops/issues/3047
> feat(database): upgrade to postgres 16

- .github/renovate-bot.json5
- .github/renovate.json5
- .github/workflows/schedule-renovate.yaml
- update depcreated config
- disable vulnerability alerts
- switch to self hosted runner
- switch back to debug :-)
> feat(renovate): adaptions

- kubernetes/kube-nas/apps/auth-system/oauth2-proxy/app/helm-release.yaml
- kubernetes/kube-nas/flux/instance/flux-instance.yaml
> fix(flux): typo :(

- kubernetes/talos-flux/apps/networking/external-dns/flux-sync.yaml
it creates more harm when deleting critical items
> fix(external-dns): disable opnsense external dns for now

- kubernetes/talos-flux/apps/github/actions-runner-controller/runners/jazzlyn/gh-actions-demo.yaml
- kubernetes/talos-flux/apps/github/actions-runner-controller/runners/jazzlyn/kind-flux-demo.yaml
- kubernetes/talos-flux/apps/github/actions-runner-controller/runners/organization/techtales-io.yaml
- kubernetes/talos-flux/apps/github/actions-runner-controller/runners/tyriis/home-ops.yaml
- kubernetes/talos-flux/apps/github/actions-runner-controller/runners/tyriis/homeassistant-config.yaml
- kubernetes/talos-flux/apps/github/actions-runner-controller/runners/tyriis/terraform-github.yaml
https://github.com/actions/actions-runner-controller/blob/4ca37fbdf29072456b18eb604d2c4e5f69bc5381/charts/gha-runner-scale-set/values.yaml#L122
> fix(arc): metrics

- kubernetes/kube-nas/apps/secops/openbao/app/persistent-volume-claim.yaml
- kubernetes/talos-flux/apps/default/homepage/app/external-secret.yaml
> feat(openbao): restore from openbao backup

- kubernetes/talos-flux/apps/gaming/minecraft-java/global-secrets/external-secrets/curseforge-api-key.yaml
- kubernetes/talos-flux/apps/gaming/minecraft-java/global-secrets/external-secrets/minecraft-bluemap-postgres.yaml
- kubernetes/talos-flux/apps/gaming/minecraft-java/global-secrets/external-secrets/minecraft-proxy-forwarding.yaml
- kubernetes/talos-flux/apps/gaming/minecraft-java/global-secrets/external-secrets/minecraft-rcon.yaml
> fix(external-secrets): adjust secretStoreRef for gaming/minecraft-java

- kubernetes/talos-flux/apps/auth-system/oauth2-proxy/app/external-secret.yaml
- kubernetes/talos-flux/apps/auth-system/oauth2-proxy/app/helm-release.yaml
> feat(external-secrets): migrate auth-system/oauth2-proxy to openbao

- kubernetes/talos-flux/apps/home-automation/ring-mqtt/app/external-secret.yaml
- kubernetes/talos-flux/apps/home-automation/zigbee2mqtt/app/external-secret.yaml
> feat(external-secrets): migrate home-automation to openbao

- kubernetes/talos-flux/apps/networking/external-dns/cloudflare/external-secret.yaml
- kubernetes/talos-flux/apps/networking/external-dns/opnsense/external-secret.yaml
- kubernetes/talos-flux/apps/networking/playit/app/external-secret.yaml
> feat(external-secrets): migrate networking to openbao

- kubernetes/talos-flux/apps/observability/opnsense-exporter/app/external-secrets.yaml
> feat(external-secrets): migrate observability to openbao

- kubernetes/talos-flux/apps/productivity/linkwarden/app/external-secret.yaml
> feat(external-secrets): migrate productivity to openbao

- kubernetes/kube-nas/apps/secops/external-secrets/stores/cluster-secret-store.yaml
> fix(openbao): adjust kube-nas backend config

- infra/terraform/README.md
- kubernetes/kube-nas/apps/secops/openbao/flux-sync.yaml
- kubernetes/kube-nas/apps/secops/openbao/snapshots/external-secret.yaml
- kubernetes/kube-nas/apps/secops/openbao/snapshots/helm-release.yaml
- kubernetes/kube-nas/apps/secops/openbao/snapshots/kustomization.yaml
> feat(openbao): setup snapshots

- kubernetes/talos-flux/apps/networking/cloudflared/app/config.yaml
> feat(atlantis): setup cloudflared tunnel for

- infra/talos/talconfig.yaml
- kubernetes/talos-flux/apps/system-upgrade/kustomization.yaml
- kubernetes/talos-flux/apps/system-upgrade/namespace.yaml
- kubernetes/talos-flux/apps/system-upgrade/system-upgrade-controller/app/helm-release.yaml
- kubernetes/talos-flux/apps/system-upgrade/system-upgrade-controller/app/kustomization.yaml
- kubernetes/talos-flux/apps/system-upgrade/system-upgrade-controller/app/rbac.yaml
- kubernetes/talos-flux/apps/system-upgrade/system-upgrade-controller/flux-sync.yaml
- kubernetes/talos-flux/apps/system-upgrade/system-upgrade-controller/plans/kubernetes.yaml
- kubernetes/talos-flux/apps/system-upgrade/system-upgrade-controller/plans/kustomization.yaml
- kubernetes/talos-flux/apps/system-upgrade/system-upgrade-controller/plans/talos.yaml
system-upgrade-controller
- copied mostly from https://github.com/bjw-s-labs/home-ops/tree/main/kubernetes/apps/system-upgrade
> feat(system-upgrade): implemented talos + kubernetes upgrades with

- infra/talos/talconfig.yaml
- kubernetes/talos-flux/apps/system-upgrade/system-upgrade-controller/flux-sync.yaml
> Revert "feat(container): update image ghcr.io/siderolabs/kubelet ( v1.32.3 → v1.33.0 )"

- kubernetes/kube-nas/apps/kube-system/cilium/app/helm-release.yaml
- kubernetes/kube-nas/bootstrap/cilium/kustomization.yaml
- kubernetes/talos-flux/apps/kube-system/cilium/app/helm-release.yaml
- kubernetes/talos-flux/bootstrap/cilium/kustomization.yaml
Reverts tyriis/home-ops#5195
https://github.com/cilium/cilium/issues/39566
> Revert "fix(deps): update helm release cilium ( 1.17.3 → 1.17.4 )"

- kubernetes/kube-nas/apps/secops/external-secrets/stores/cluster-secret-store.yaml
- kubernetes/kube-nas/apps/secops/openbao/snapshots/external-secret.yaml
- kubernetes/talos-flux/apps/atlantis/techtales-io/terraform-gcloud/external-secret.yaml
- kubernetes/talos-flux/apps/atlantis/techtales-io/terraform-github/external-secret.yaml
- kubernetes/talos-flux/apps/atlantis/techtales-io/terraform-gworkspace/external-secret.yaml
- kubernetes/talos-flux/apps/atlantis/techtales-io/terraform-vault/external-secret.yaml
- kubernetes/talos-flux/apps/atlantis/tyriis/terraform-github/external-secret.yaml
- kubernetes/talos-flux/apps/auth-system/oauth2-proxy/app/external-secret.yaml
- kubernetes/talos-flux/apps/default/homepage/app/external-secret.yaml
- kubernetes/talos-flux/apps/gaming-public/minecraft-java/global-secrets/external-secrets/curseforge-api-key.yaml
- kubernetes/talos-flux/apps/gaming-public/minecraft-java/global-secrets/external-secrets/minecraft-proxy-forwarding.yaml
- kubernetes/talos-flux/apps/gaming-public/minecraft-java/global-secrets/external-secrets/minecraft-rcon.yaml
- kubernetes/talos-flux/apps/gaming-public/minecraft-java/velocity-proxy/external-secret.yaml
- kubernetes/talos-flux/apps/gaming/minecraft-java/global-secrets/external-secrets/curseforge-api-key.yaml
- kubernetes/talos-flux/apps/gaming/minecraft-java/global-secrets/external-secrets/minecraft-bluemap-postgres.yaml
- kubernetes/talos-flux/apps/gaming/minecraft-java/global-secrets/external-secrets/minecraft-proxy-forwarding.yaml
- kubernetes/talos-flux/apps/gaming/minecraft-java/global-secrets/external-secrets/minecraft-rcon.yaml
- kubernetes/talos-flux/apps/home-automation/n8n/app/external-secret.yaml
- kubernetes/talos-flux/apps/home-automation/ring-mqtt/app/external-secret.yaml
- kubernetes/talos-flux/apps/home-automation/zigbee2mqtt/app/external-secret.yaml
- kubernetes/talos-flux/apps/networking/external-dns/cloudflare/external-secret.yaml
- kubernetes/talos-flux/apps/networking/external-dns/opnsense/external-secret.yaml
- kubernetes/talos-flux/apps/networking/playit/app/external-secret.yaml
- kubernetes/talos-flux/apps/observability/opnsense-exporter/app/external-secrets.yaml
- kubernetes/talos-flux/apps/observability/unpoller/app/external-secret.yaml
- kubernetes/talos-flux/apps/productivity/linkwarden/app/external-secret.yaml
- kubernetes/talos-flux/apps/secops/external-secrets/stores/cluster-secret-store.yaml
https://github.com/tyriis/home-ops/pull/5189
> fix(external-secrets): migrate to api v1

- kubernetes/kube-nas/apps/flux-system/flux/webhook/kustomization.yaml
- kubernetes/kube-nas/apps/flux-system/flux/webhook/receiver.yaml
> chore(flux): add receiver as yaml manifest maybe there is a better way

- kubernetes/talos-flux/apps/gaming-public/minecraft-java/velocity-proxy/helm-release.yaml
- kubernetes/talos-flux/apps/gaming/minecraft-java/velocity-proxy/helm-release.yaml
> Revert "chore(container): update image itzg/mc-proxy ( 02a50a9 → 7d27baf )"

- kubernetes/kube-nas/apps/flux-system/flux/webhook/helm-release.yaml
> feat(flux): remove cluster secrets by migrating cloudflare tunnel to

- kubernetes/talos-flux/apps/networking/cloudflared/app/config.yaml
> feat(gatus): setup cloudflared tunnel config

- kubernetes/talos-flux/apps/observability/gatus/app/helm-release.yaml
- because i am paranoid
- part of #5119
> fix(gatus): sidecar only watch for cm not for secrets

- kubernetes/talos-flux/apps/observability/kromgo/app/helm-release.yaml
- kubernetes/talos-flux/apps/observability/kromgo/flux-sync.yaml
> feat(gatus): add kromgo entry point

- kubernetes/talos-flux/apps/auth-system/oauth2-proxy/app/helm-release.yaml
- kubernetes/talos-flux/apps/default/echo-server/app/helm-release.yaml
thanks to https://github.com/ShadyF/k8s-homelab/blob/master/docs/apps/oauth2-proxy.md?plain=1
> fix(oauth2-proxy): lets see if this helps

- kubernetes/talos-flux/apps/gaming-public/minecraft-java/velocity-proxy/config/plugins.txt
- kubernetes/talos-flux/apps/gaming/minecraft-java/creative-world/config/plugins.txt
- kubernetes/talos-flux/apps/gaming/minecraft-java/lobby-world/config/plugins.txt
- kubernetes/talos-flux/apps/gaming/minecraft-java/playground-world/config/plugins.txt
- kubernetes/talos-flux/apps/gaming/minecraft-java/survival-world/config/plugins.txt
- kubernetes/talos-flux/apps/gaming/minecraft-java/velocity-proxy/config/plugins.txt
> feat(minecraft): use modrinth for plugins, maybe switch to hangar at

- kubernetes/talos-flux/apps/observability/gatus/app/helm-release.yaml
> Revert "feat(container): update image ghcr.io/twin/gatus ( v5.17.0 → v5.18.0 )"

- kubernetes/base/flux/repositories/git/dragonfly-operator.yaml
- kubernetes/talos-flux/apps/database/cloudnative-pg/flux-sync.yaml
- kubernetes/talos-flux/apps/database/cloudnative-pg/git-repository.yaml
- kubernetes/talos-flux/apps/database/kustomization.yaml
> fix(cnpg): added crds for objectstore

- kubernetes/talos-flux/apps/database/cloudnative-pg/cluster/cluster17.yaml
- kubernetes/talos-flux/apps/database/cloudnative-pg/cluster/objectstore.yaml
- kubernetes/talos-flux/apps/database/cloudnative-pg/cluster/postgres-minio-secret.sops.yaml
> feat(cnpg): setup new cluster

- kubernetes/talos-flux/apps/database/cloudnative-pg/cluster/objectstore.yaml
> fix(cnpg): maybe?

- kubernetes/talos-flux/apps/database/cloudnative-pg/cluster/database-server.yaml
> feat(dbman): adopt new database

- kubernetes/talos-flux/apps/home-automation/home-assistant/app/database.yaml
- kubernetes/talos-flux/apps/home-automation/home-assistant/app/kustomization.yaml
- kubernetes/talos-flux/apps/productivity/linkwarden/app/database.yaml
- kubernetes/talos-flux/apps/windmill/windmill/app/database.yaml
> feat(dbman): init new home-assistant db

- kubernetes/talos-flux/apps/productivity/linkwarden/app/external-secret.yaml
- kubernetes/talos-flux/apps/windmill/windmill/app/external-secret.yaml
> feat(cnpg): finalize migration

- kubernetes/kube-nas/apps/ingress-nginx/ingress-nginx/app/helm-release.yaml
- kubernetes/talos-flux/apps/gaming-public/minecraft-java/velocity-proxy/helm-release.yaml
- kubernetes/talos-flux/apps/home-automation/emqx/app/helm-release.yaml
- kubernetes/talos-flux/apps/networking/adguard-home/app/helm-release.yaml
- kubernetes/talos-flux/apps/networking/unifi-controller/app/helm-release.yaml
- kubernetes/talos-flux/apps/productivity/syncthing/app/helm-release.yaml
- kubernetes/talos-flux/apps/traefik-ingress/traefik/app/helm-release.yaml
- https://docs.cilium.io/en/stable/network/lb-ipam/#requesting-ips
> feat(cilium): adjust service annotation

- kubernetes/talos-flux/apps/gaming/minecraft-java/velocity-proxy/config/plugins.txt
- kubernetes/talos-flux/apps/gaming/minecraft-java/velocity-proxy/helm-release.yaml
- kubernetes/talos-flux/apps/gaming/minecraft-java/velocity-proxy/kustomization.yaml
- kubernetes/talos-flux/apps/gaming/minecraft-java/velocity-proxy/plugins/velocityrcon/rcon.toml
- workaround for: https://github.com/itzg/docker-mc-proxy/issues/248
- deactivate rcon and install via plugin system
> feat(minecraft): workaround for rcon velocity plugin problem

- kubernetes/talos-flux/apps/gaming/minecraft-java/velocity-proxy/config/plugins.txt
- kubernetes/talos-flux/apps/gaming/minecraft-java/velocity-proxy/helm-release.yaml
- kubernetes/talos-flux/apps/gaming/minecraft-java/velocity-proxy/kustomization.yaml
- kubernetes/talos-flux/apps/gaming/minecraft-java/velocity-proxy/plugins/velocityrcon/rcon.toml
- resolved in https://github.com/itzg/docker-mc-proxy/issues/248
> fix(minecraft): revert rcon workaround

- .taskfiles/devenv/flux.yaml
- devenv/oci/apps/cert-manager/cert-manager/app/kustomization.yaml
- devenv/oci/apps/cert-manager/cert-manager/flux-sync.yaml
- devenv/oci/apps/cert-manager/cert-manager/issuers/kustomization.yaml
- devenv/oci/apps/cert-manager/kustomization.yaml
- devenv/oci/apps/cert-manager/namespace.yaml
- devenv/oci/apps/flux-system/flux-operator/flux-sync.yaml
- devenv/oci/apps/flux-system/namespace.yaml
- devenv/oci/apps/ingress-nginx/ingress-nginx/flux-sync.yaml
- devenv/oci/apps/ingress-nginx/kustomization.yaml
- devenv/oci/apps/ingress-nginx/namespace.yaml
- devenv/oci/apps/kube-system/metrics-server/flux-sync.yaml
- devenv/oci/apps/kube-system/namespace.yaml
- devenv/oci/apps/kube-tools/i-see-dead-pods/flux-sync.yaml
- devenv/oci/apps/kube-tools/kustomization.yaml
- devenv/oci/apps/kube-tools/namespace.yaml
- devenv/oci/apps/kube-tools/reloader/flux-sync.yaml
- devenv/oci/flux/config/cluster-settings.yaml
- devenv/oci/flux/kustomization.yaml
- devenv/oci/registry-config.yaml
> feat(devenv): restructure apps

- kubernetes/talos-flux/apps/github/actions-runner-controller/operator/helm-release.yaml
- kubernetes/talos-flux/apps/github/actions-runner-controller/runners/jazzlyn/gh-actions-demo.yaml
- kubernetes/talos-flux/apps/github/actions-runner-controller/runners/jazzlyn/kind-flux-demo.yaml
- kubernetes/talos-flux/apps/github/actions-runner-controller/runners/organization/techtales-io.yaml
- kubernetes/talos-flux/apps/github/actions-runner-controller/runners/tyriis/home-ops.yaml
- kubernetes/talos-flux/apps/github/actions-runner-controller/runners/tyriis/homeassistant-config.yaml
- kubernetes/talos-flux/apps/github/actions-runner-controller/runners/tyriis/terraform-github.yaml
- kubernetes/talos-flux/apps/github/actions-runner-controller/runners/tyriis/terraform-github/helm-release.yaml
> Revert "feat(github-runners): update group ( 0.11.0 → 0.12.0 )"

- .github/renovate.json5
> feat(renovate): app template pr per cluster #5290

- kubernetes/talos-flux/apps/cnpg-system/namespace.yaml
try to prevent backups each hour
> fix(cnpg): prevent k8tz injection for namespace

- kubernetes/kube-nas/apps/cnpg-system/namespace.yaml
> fix(cnpg): prevent k8tz injection in cnpg-system

- kubernetes/kube-nas/apps/cnpg-system/cnpg/cluster/crd/scheduled-backup.yaml
- kubernetes/talos-flux/apps/cnpg-system/cnpg/cluster/scheduled-backup.yaml
part of: https://github.com/tyriis/home-ops/issues/5985
> fix(cnpg): backup does not work properly with cron based annotation

- kubernetes/base/apps/minecraft/paper-server/helm-release.yaml
> fix(minecraft): increase upgrade timeout #6116

- kubernetes/kube-lab/apps/home-automation/home-assistant/app/helm-release.yaml
- kubernetes/talos-flux/apps/home-automation/home-assistant/app/helm-release.yaml
- switch over domains as arround 80% is working
> feat(home-assistant): migrate to kube-lab
